version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: lasavo
      POSTGRES_PASSWORD: lasavo123
      POSTGRES_DB: lasavo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://lasavo:lasavo123@db:5432/lasavo_db
      SECRET_KEY: secretlasavo

volumes:
  postgres_data:
